name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération de notre code (Task et Test)
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installation des dépendances qu'on a besoins
        run: npm install

      - name: Exécution des tests du fichier test
        run: npm test
